#include "Kits.h"


const array<ChromaticScale, NUM_KITS> default_kit_data = {
	{
		{0  +(5 * 12), ChromaticScale::ScaleTypes::MAJOR},
		{1  +(5 * 12), ChromaticScale::ScaleTypes::MAJOR},
		{2  +(5 * 12), ChromaticScale::ScaleTypes::MAJOR},
		{3  +(5 * 12), ChromaticScale::ScaleTypes::MAJOR},
		{4  +(5 * 12), ChromaticScale::ScaleTypes::MAJOR},
		{5  +(5 * 12), ChromaticScale::ScaleTypes::MAJOR},
		{6  +(5 * 12), ChromaticScale::ScaleTypes::MAJOR},
		{7  +(5 * 12), ChromaticScale::ScaleTypes::MAJOR},
		{8  +(5 * 12), ChromaticScale::ScaleTypes::MAJOR},
		{9  +(5 * 12), ChromaticScale::ScaleTypes::MAJOR},
		{10 +(5 * 12), ChromaticScale::ScaleTypes::MAJOR},
		{11 +(5 * 12), ChromaticScale::ScaleTypes::MAJOR},
		{0  +(5 * 12), ChromaticScale::ScaleTypes::NATURAL_MINOR},
		{1  +(5 * 12), ChromaticScale::ScaleTypes::NATURAL_MINOR},
		{2  +(5 * 12), ChromaticScale::ScaleTypes::NATURAL_MINOR},
		{3  +(5 * 12), ChromaticScale::ScaleTypes::NATURAL_MINOR},
		{4  +(5 * 12), ChromaticScale::ScaleTypes::NATURAL_MINOR},
		{5  +(5 * 12), ChromaticScale::ScaleTypes::NATURAL_MINOR},
		{6  +(5 * 12), ChromaticScale::ScaleTypes::NATURAL_MINOR},
		{7  +(5 * 12), ChromaticScale::ScaleTypes::NATURAL_MINOR},
		{8  +(5 * 12), ChromaticScale::ScaleTypes::NATURAL_MINOR},
		{9  +(5 * 12), ChromaticScale::ScaleTypes::NATURAL_MINOR},
		{10 +(5 * 12), ChromaticScale::ScaleTypes::NATURAL_MINOR},
		{11 +(5 * 12), ChromaticScale::ScaleTypes::NATURAL_MINOR},
		{0  +(5 * 12), ChromaticScale::ScaleTypes::DORIAN},
		{1  +(5 * 12), ChromaticScale::ScaleTypes::DORIAN},
		{2  +(5 * 12), ChromaticScale::ScaleTypes::DORIAN},
		{3  +(5 * 12), ChromaticScale::ScaleTypes::DORIAN},
		{4  +(5 * 12), ChromaticScale::ScaleTypes::DORIAN},
		{5  +(5 * 12), ChromaticScale::ScaleTypes::DORIAN},
		{6  +(5 * 12), ChromaticScale::ScaleTypes::DORIAN},
		{7  +(5 * 12), ChromaticScale::ScaleTypes::DORIAN},
		{8  +(5 * 12), ChromaticScale::ScaleTypes::DORIAN},
		{9  +(5 * 12), ChromaticScale::ScaleTypes::DORIAN},
		{10 +(5 * 12), ChromaticScale::ScaleTypes::DORIAN},
		{11 +(5 * 12), ChromaticScale::ScaleTypes::DORIAN},
		{0  +(5 * 12), ChromaticScale::ScaleTypes::LYDIAN},
		{1  +(5 * 12), ChromaticScale::ScaleTypes::LYDIAN},
		{2  +(5 * 12), ChromaticScale::ScaleTypes::LYDIAN},
		{3  +(5 * 12), ChromaticScale::ScaleTypes::LYDIAN},
		{4  +(5 * 12), ChromaticScale::ScaleTypes::LYDIAN},
		{5  +(5 * 12), ChromaticScale::ScaleTypes::LYDIAN},
		{6  +(5 * 12), ChromaticScale::ScaleTypes::LYDIAN},
		{7  +(5 * 12), ChromaticScale::ScaleTypes::LYDIAN},
		{8  +(5 * 12), ChromaticScale::ScaleTypes::LYDIAN},
		{9  +(5 * 12), ChromaticScale::ScaleTypes::LYDIAN},
		{10 +(5 * 12), ChromaticScale::ScaleTypes::LYDIAN},
		{11 +(5 * 12), ChromaticScale::ScaleTypes::LYDIAN},
		{0  +(5 * 12), ChromaticScale::ScaleTypes::MIXOLYDIAN},
		{1  +(5 * 12), ChromaticScale::ScaleTypes::MIXOLYDIAN},
		{2  +(5 * 12), ChromaticScale::ScaleTypes::MIXOLYDIAN},
		{3  +(5 * 12), ChromaticScale::ScaleTypes::MIXOLYDIAN},
		{4  +(5 * 12), ChromaticScale::ScaleTypes::MIXOLYDIAN},
		{5  +(5 * 12), ChromaticScale::ScaleTypes::MIXOLYDIAN},
		{6  +(5 * 12), ChromaticScale::ScaleTypes::MIXOLYDIAN},
		{7  +(5 * 12), ChromaticScale::ScaleTypes::MIXOLYDIAN},
		{8  +(5 * 12), ChromaticScale::ScaleTypes::MIXOLYDIAN},
		{9  +(5 * 12), ChromaticScale::ScaleTypes::MIXOLYDIAN},
		{10 +(5 * 12), ChromaticScale::ScaleTypes::MIXOLYDIAN},
		{11 +(5 * 12), ChromaticScale::ScaleTypes::MIXOLYDIAN},
		{0 + (5 * 12), ChromaticScale::ScaleTypes::PHRYGIAN},
		{1 + (5 * 12), ChromaticScale::ScaleTypes::PHRYGIAN},
		{2 + (5 * 12), ChromaticScale::ScaleTypes::PHRYGIAN},
		{3 + (5 * 12), ChromaticScale::ScaleTypes::PHRYGIAN},
	}
};
